# Generated by Django 3.1.7 on 2021-03-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster_path',
            field=models.CharField(default='a', max_length=300),
            preserve_default=False,
        ),
    ]
