# Generated by Django 3.1.7 on 2021-03-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_poster_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
